version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-west-2:555918697305:task-definition/aws-hello-world-rest-api-service:1"
        LoadBalancerInfo:
          ContainerName: "aws-hello-world-rest-api-service"
          ContainerPort: "80"
        PlatformVersion: "LATEST"